# Configuration du logiciel

class sudo::config inherits sudo
{
  
  file { $file_name :
        #path                  => $file_path,
			  ensure                => $file_ensure,
			  backup                => $file_backup,
			  #checksum             => $file_checksum,
			  content               => template("sudo/sudoers.erb"),    
			  #ctime                => $file_ctime,
			  #force                => $file_force,
			  group                 => $file_group,
			  #ignore               => $file_ignore,
			  #links                => $file_links, 
			  mode                  => $file_mode,
			  #mtime                => $file_mtime,
			  owner                 => $file_owner,
			  #provider             => $file_provider,
			  #purge                => $file_purge,
			  #recurse              => $file_recurse,
			  #recurselimit         => $file_recurselimit,
			  replace               => $file_replace,
			  #selinux_ignore_defaults => $file_selinux_ignore_defaults,
			  #selrange             => $file_selrange,
			  #selrole              => $file_selrole,
			  #seltype              => $file_seltype,
			  #seluser              => $file_seluser,
			  #show_diff            => $file_show_diff,
			  #source               => $file_source,
			  #source_permissions   => $file_source_permissions,
			  #sourceselect         => $file_sourceselect,
			  #target               => $file_target,
			  #validate_cmd         => $file_validate_cmd,
			  #validate_replacement => $file_validate_replacement,
			  require               => Package[$package_name],
			  }
			  
file { $dir_name :
        #path                  => $dir_path,
        ensure                => $dir_ensure,
        #backup               => $dir_backup,
        #checksum             => $dir_checksum,
        #content              => template($file_content),    
        #ctime                => $dir_ctime,
        #force                => $dir_force,
        group                 => $dir_group,
        #ignore               => $dir_ignore,
        #links                => $dir_links, 
        mode                  => $dir_mode,
        #mtime                => $dir_mtime,
        owner                 => $dir_owner,
        #provider             => $dir_provider,
        #purge                => $dir_purge,
        #recurse              => $dir_recurse,
        #recurselimit         => $dir_recurselimit,
        #replace              => $dir_replace,
        #selinux_ignore_defaults => $dir_selinux_ignore_defaults,
        #selrange             => $dir_selrange,
        #selrole              => $dir_selrole,
        #seltype              => $dir_seltype,
        #seluser              => $dir_seluser,
        #show_diff            => $dir_show_diff,
        #source               => $dir_source,
        #source_permissions   => $dir_source_permissions,
        #sourceselect         => $dir_sourceselect,
        #target               => $dir_target,
        #validate_cmd         => $dir_validate_cmd,
        #validate_replacement => $dir_validate_replacement,
        require               => Package[$package_name],
        }
  
}